### ISSUE TITLE
Postman collection and blob data for sample data seeding

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspaceFork#109]
Feature agera-edc/MinimumViableDataspaceOld#30

## Description
Initial sample data is needed for newly deployed MVD connectors. For sample see [CatalogDataseedingExtension](https://github.com/agera-edc/edc-showcase/blob/main/extensions/dataseeding/catalog/src/main/java/org/eclipse/dataspaceconnector/dataseeding/catalog/CatalogDataseedingExtension.java)

## Acceptance Criteria

- [ ] Provide postman collection for uploading assets, policies and contract offers/definition.
- [ ] Updated CD to provision test data (per participant).
- [ ] Updated CD to seed sample data to deployed connectors. Newman(postman headless runner) can be used to execute collection.

## Tasks

- [ ] Adapt Terraform code to provision a storage account, a container, and a blob with sample text data.
- [ ] Adapt Terraform code to provision a key vault, with a secret containing the data storage account key. Grant the EDC Application read access to the secret
- [ ] Build postman collection for uploading assets, policies and contract offers/definition. Include tests for successful (idempotent) upload
- [ ] Run Newman to provision data in each deployment.
