### ISSUE TITLE
Add checkstyle for MVD, Registration Service and Identity Service

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspaceFork#6]
## Description

Add checkstyle for MVD, Registration Service and Identity Service/repo. Github workflow should also run checkstyle during build.

e.g. 

- Config: https://github.com/agera-edc/DataSpaceConnector/blob/main/resources/edc-checkstyle-config.xml
- Workflow check: https://github.com/agera-edc/DataSpaceConnector/blob/090ae3ea73e63cb6c47d356cb5753b17c57b64ac/.github/workflows/verify.yaml#L18

## Acceptance Criteria

- [x] Add checkstyle config to MVD, Registration Service and Identity Service.
- [x] Update github workflow to run checkstyle during build.

## Tasks

- [ ] Add checkstyle config to repos (3 separate PRs)
