### ISSUE TITLE
UI Design for Creating Data Contract

### ISSUE THREAD

**Issue by JankaKoen** [agera-edc/MinimumViableDataspaceFork#64]
## Description
UI for the MVD in Figma for Creating a Dataspace

## Tasks
- [ ] Rebuild the UI into Stepper
- [ ] Add Search function for the policies/assets
- [ ] Create Unhappy Path (Policies in Conflict)
- [ ] Policy - change the UI to support just one

**Comment by zeier** [comment]
HX items will be tracked elsewhere.
